input_data_path: "data/raw/heart.csv"
output_model_path: "models/log_reg.pkl"
metric_path: "metrics/metrics_log_reg.json"
splitting_params:
  val_size: 0.25
  random_state: 42
train_params:
  model_type: "LogisticRegression"
feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop:
    - "fbs"
  target_col:
    - "target"
