# @package _group_
input_data_path: "../../data/raw/heart.csv"
metric_dir: "metrics"
model_dir: "models"
random_state: 42

feature_params:
  categorical_features:
    - "sex"
    - "cp"
    - "restecg"
    - "exang"
    - "slope"
    - "ca"
    - "thal"
  numerical_features:
    - "age"
    - "trestbps"
    - "chol"
    - "thalach"
    - "oldpeak"
  features_to_drop:
    - "fbs"
  target_col:
    - "target"

