apiVersion: v1
kind: Pod
metadata:
  name: online-inference
spec:
  containers:
    - image: markhubbatulin/online_inference:v1
      name: online-inference
      ports:
        - containerPort: 8000
